font = "Hasklug Nerd Font"
icons = "awesome"

[theme]
name="slick"
[theme.overrides]
idle_bg = "#232629"

[[block]]
block = "focused_window"
max_width = 100

[[block]]
block = "battery"
driver = "upower"
format = "{percentage}%"

[[block]]
block = "sound"
driver = "pulseaudio"
on_click = "pavucontrol-qt"

[[block]]
block = "music"
buttons = ["play", "next"]

[[block]]
block = "bluetooth"
mac = "BC:F2:92:CA:6A:3F"

[[block]]
block="net"
device = "wlp2s0"
signal_strength = true
interval = 3

[[block]]
block = "time"
format = "%m-%d %H:%M"
